# Generated by Django 3.1.1 on 2021-09-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, db_index=True, max_length=16, null=True, unique=True)),
                ('verification', models.CharField(default='register', max_length=8)),
                ('email', models.CharField(db_index=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(default='', max_length=256)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
