# Generated by Django 3.1.1 on 2021-09-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210920_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification',
            field=models.CharField(default='full', max_length=8),
        ),
    ]
