# Generated by Django 3.1.1 on 2021-09-20 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance_api_v1', '0002_auto_20210920_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_profile', to='finance_api_v1.financeprofile'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_profile', to='finance_api_v1.financeprofile'),
        ),
    ]
